In [1]:
import tensorflow as tf

# Random Tensors

In [2]:
# Create random Tensor

random = tf.random.Generator.from_seed(10) # Seed is for reproducibility
random = random.normal(shape = (2, 2))

random

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.29604465, -0.21134205],
       [ 0.01063002,  1.5165398 ]], dtype=float32)>

#### Two random (But same) Tensors

In [3]:
# Now we create two random (but the same) Tensors

random_1 = tf.random.Generator.from_seed(20)
random_1 = random_1.normal(shape = (3, 3))

random_2 = tf.random.Generator.from_seed(20)
random_2 = random_2.normal(shape = (3, 3))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ,  0.86754173],
        [-0.19625713, -1.322665  , -0.02279496],
        [-0.1383193 ,  0.44207528, -0.7531523 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ,  0.86754173],
        [-0.19625713, -1.322665  , -0.02279496],
        [-0.1383193 ,  0.44207528, -0.7531523 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

#### Shufle the order of the elements in Tensors

In [4]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order dosen't effect learning)

not_shuffled = tf.constant([
    [8, 2, 10],
    [5, 6, 1],
    [4, 9, 3]
])

not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 8,  2, 10],
       [ 5,  6,  1],
       [ 4,  9,  3]])>

In [5]:
# shuffle our non-shuffled Tensor
# Randomly shuffle a tensor along it's first dimension

shuffle = tf.random.shuffle(not_shuffled)

shuffle

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  9,  3],
       [ 8,  2, 10],
       [ 5,  6,  1]])>

In [6]:
# tf.random.set_seed(10)

shuffle = tf.random.shuffle(not_shuffled, seed = 20)

shuffle

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 8,  2, 10],
       [ 5,  6,  1],
       [ 4,  9,  3]])>

### Shuffling Tensors

In [7]:
not_shuffled_1 = tf.constant([
    [4, 2],
    [10, 9],
    [7, 8]
])

not_shuffled_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  2],
       [10,  9],
       [ 7,  8]])>

In [8]:
tf.random.set_seed(30)

shuffled_1 = tf.random.shuffle(not_shuffled_1)

shuffled_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  2],
       [ 7,  8],
       [10,  9]])>

##### 1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
##### 2. If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
##### 3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
##### 4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [9]:
not_shuffled_2 = tf.constant([
    [5, 2, 1, 6, 8],
    [6, 4, 1, 5, 7],
    [7, 3, 8, 3,1]
])

tf.random.set_seed(42)

tf.random.shuffle(not_shuffled_2)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[6, 4, 1, 5, 7],
       [7, 3, 8, 3, 1],
       [5, 2, 1, 6, 8]])>

##### If we want our shuffled tensors to be in same order everytime, we've got to use both global and  operational level random seeds

### Other ways to make tensors

In [10]:
# Create  a tensors of all ones

tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [11]:
# create a tensors of all zeros

tf.zeros([2, 10], tf.float16)

<tf.Tensor: shape=(2, 10), dtype=float16, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float16)>

#### Turn numpy arrays into Tensors

##### The main difference between numpy arrays and  tensorflow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [12]:

import numpy as np

array_A = np.array([
    [4, 2, 5, 1],
    [5, 1, 2, 5],
    [0, 7, 4, 7]
])

# X = tf.constant(some_matrix) :: variable name  is capital  because of matrix or Tensors
# y = tf.constant(vector) :: smaller for vectors


tensor_T = tf.constant(array_A)

tensor_T

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[4, 2, 5, 1],
       [5, 1, 2, 5],
       [0, 7, 4, 7]])>

In [13]:
# Numpy array using arrange method

array_A = np.arange(1, 25, dtype = np.int32) # Create a numpy array from 1 to 24, having float32 data type

tensor_T = tf.constant(array_A)

tensor_T

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [14]:
# We can also change the shape of the tensor while converting numpy array to tensors

tensor_T = tf.constant(array_A, shape = (2, 3, 4))

tensor_T

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

## Getting Information from tensors

When dealing with tensors you probably want to be aware of the following attributes:

* 1. Shape

* 2. Rank

* 3. Axis or Dimensions

* 4. Size


In [15]:
# Create a rank 4 tensors(4 dimensions)

rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [16]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [17]:
# Get various attributes of our tensors

print("Datatype of every element in Tensor : ", rank_4_tensor.dtype)
print("Shape of Tensor : ", rank_4_tensor.shape)
print("Total number of elements in Tensor : ", tf.size(rank_4_tensor).numpy())
print("Dimensions (Rank) of Tensor : ", rank_4_tensor.ndim)
print("Elements along the 0 axis : ", rank_4_tensor.shape[0])
print("Elements along the last axis : ", rank_4_tensor.shape[-1])

Datatype of every element in Tensor :  <dtype: 'float32'>
Shape of Tensor :  (2, 3, 4, 5)
Total number of elements in Tensor :  120
Dimensions (Rank) of Tensor :  4
Elements along the 0 axis :  2
Elements along the last axis :  5


#### Indexing Tensors

Tensors can be indexed just like Python lists.

In [18]:
# Get the first two elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [19]:
# Get the first element from each dimension from each index except for the final one

rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [20]:
# Create a rank 2 tensor (2 dimensions)

rank_2_tensor = tf.constant([
    [10, 7],
    [7, 10]
])

# Get the last time of eachof our rank 2 tensor

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [21]:
# Add in extra dimension to our rank 2 Tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]

rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]])>

In [22]:
# Alternative of tf.newaxis

tf.expand_dims(rank_2_tensor, axis = -1) # -1 means expand from end

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]])>

In [23]:
tf.expand_dims(rank_2_tensor, axis = 0) # Expand 0th axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 7, 10]]])>

In [24]:
# Original array is unchaged

rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

### Manipulating Tensors(tensor operation)

**Basic Operations**

`+`, `-`, `*`, `/`

In [25]:
# You can add values to tensors using addition operators

tensor = tf.constant([
    [7, 10],
    [5, 9]
])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 20],
       [15, 19]])>

In [26]:
# Original tensor is unchanged

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 5,  9]])>

In [27]:
# Multiplication

tensor = tf.constant([
    [5, 10],
    [2, 4]
])

tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [ 4,  8]])>

In [28]:
# Division

tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2.5, 5. ],
       [1. , 2. ]])>

In [29]:
# Subtraction 

tensor - 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 8],
       [0, 2]])>

In [30]:
# we can use tensorflow built-in functions

tf.math.multiply(tensor, 10)

tf.math.subtract(tensor, 2)

tf.math.add(tensor, 10)

tf.math.divide(tensor, 2)

# It is recommended to use tensorflow buitl-in functions for speed

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2.5, 5. ],
       [1. , 2. ]])>

### Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor operation

In [31]:
# First create a simple tenosr

arr = np.array([
    [9, 8],
    [0, 7]
])

tensor_1 = tf.constant(arr)

tensor_2 = tf.constant([
    [2, 3],
    [5, 4]
])

tf.linalg.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[58, 59],
       [35, 28]])>

In [32]:
arr = np.arange(1, 10, dtype = np.int32)

tensor_1 = tf.constant(arr, shape = (3, 3))

arr = np.arange(1, 7, dtype = np.int32)

tensor_2 = tf.constant(arr, shape = (3, 2))

tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])>

In [33]:
# Matrix multiplication using python operator "@"

tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])>

To determine the final shape of matrix after multiplication

* First Matrix having shape (3, 4) == (x, y)

* Second matrix having shape (4, 2) == (y, z)

Result matrix shape is (3, 2) == (x, z)



In [34]:
arr = np.arange(0, 6)

tensor_1 = tf.constant(arr, shape = (3, 2))

arr = np.arange(6, 12)

tensor_2 = tf.constant(arr, shape = (3, 2))

# Let's change the shape of the tensor_2

tensor_2 = tf.reshape(tensor_2, shape = (2, 3))

tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 10, 11],
       [39, 44, 49],
       [69, 78, 87]])>

In [35]:
# Difference between transpose and reshape

tensor_1, tf.transpose(tensor_1), tf.reshape(tensor_1, shape = (2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3],
        [4, 5]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[0, 2, 4],
        [1, 3, 5]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[0, 1, 2],
        [3, 4, 5]])>)

#### The Dot Product

Matrix multiplication is also referred as the dot product:

* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [36]:
# Perform the dot product on the tensor_1 and tensor_2

tf.tensordot(tensor_1, tensor_2, axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 10, 11],
       [39, 44, 49],
       [69, 78, 87]])>

Generally, when performing matrix multiplication on two tensors and one of the axes dosen't line up,
you will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.

## Changing the data type of the Tensors

In [37]:
# Create a new Tensor with default data type (float32).

A = tf.constant([1. , 4.])

A.dtype

tf.float32

In [38]:
B = tf.constant([1, 2])

B.dtype

tf.int32

In [39]:
# Let's change the data type from float32 to float16 (reduced precision)

A = tf.cast(A, dtype = tf.float16)

A.dtype

tf.float16

In [40]:
# Now, Change the data type from float16 to float32

tf.cast(A, dtype = tf.float32).dtype

tf.float32

### Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [41]:
tensor = tf.constant([
    [-23, 12],
    [2.3, -4.2]
])

tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-23. ,  12. ],
       [  2.3,  -4.2]], dtype=float32)>

In [42]:
# Get the absolute values

tf.abs(tensor)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[23. , 12. ],
       [ 2.3,  4.2]], dtype=float32)>

#### Let's go through the following forms of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a Tensor
* Get the sum of a Tensor


In [43]:
A = tf.constant(np.random.randint(0, 100, size= 50))

print("Original Tensor: \n", A)

print("\nMinimum From Tensor: \n", tf.math.reduce_min(A))

print("\nMaximum From Tensor: \n", tf.math.reduce_max(A))

print("\nMean From Tensor: \n", tf.math.reduce_mean(A))

print("\nSum of the Tensor: \n", tf.math.reduce_sum(A))

Original Tensor: 
 tf.Tensor(
[12 72 92 33 78 75 76 12 87 37 18 43 36  4 96 44 82 37 27 92 29 45 15 14
 81 54 99 10 66 72 44 47 39 50 40 40 72  1 49 42 67 44  9 19 25  7 88 96
 63 95], shape=(50,), dtype=int32)

Minimum From Tensor: 
 tf.Tensor(1, shape=(), dtype=int32)

Maximum From Tensor: 
 tf.Tensor(99, shape=(), dtype=int32)

Mean From Tensor: 
 tf.Tensor(49, shape=(), dtype=int32)

Sum of the Tensor: 
 tf.Tensor(2475, shape=(), dtype=int32)


In [44]:
# Find the variance of the Tensor

import tensorflow_probability as tfp

print(tfp.stats.variance(A))

tf.math.reduce_variance(tf.cast(A, dtype = tf.float32))




tf.Tensor(825, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=float32, numpy=825.49>

### Find the positional maximum and minimum

In [45]:
# Create a new Tensor

tf.random.set_seed(42)

A = tf.random.uniform(shape = [50])

A

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [46]:
# Find positional maximum

print("Positional Maximum: \n", tf.argmax(A))

print("\nIndex on our largest value position: \n", A[tf.argmax(A)])

print("\nCompare max value and Positional maximum: \n", A[tf.argmax(A)] == tf.math.reduce_max(A))

Positional Maximum: 
 tf.Tensor(42, shape=(), dtype=int64)

Index on our largest value position: 
 tf.Tensor(0.9671384, shape=(), dtype=float32)

Compare max value and Positional maximum: 
 tf.Tensor(True, shape=(), dtype=bool)


In [47]:
# Find Positional minimum

print("Positional minimum : \n", tf.argmin(A))

print("\nIndex on our smallest value in position: \n", A[tf.argmin(A)])

print("\nCompare min value and Positional minimum: \n", A[tf.argmin(A)] == tf.math.reduce_min(A))

assert A[tf.argmin(A)] == tf.reduce_min(A) # assert will give an error if it is not equal

Positional minimum : 
 tf.Tensor(16, shape=(), dtype=int64)

Index on our smallest value in position: 
 tf.Tensor(0.009463668, shape=(), dtype=float32)

Compare min value and Positional minimum: 
 tf.Tensor(True, shape=(), dtype=bool)


#### Practice of the Positional minimum and maximum

In [48]:
A = tf.constant(np.random.randint(1000, 10000, 50))

print("Original Tensor : \n", A)

print("\nPositional maximum : \n", tf.argmax(A))

print("\nPositional minimum : \n", tf.argmin(A))

Original Tensor : 
 tf.Tensor(
[2573 8273 7073 8384 7871 6892 3742 9310 8169 2100 2849 8117 6895 7166
 5485 5251 8613 3600 8450 2507 2530 7177 3329 4715 7056 1472 2552 8480
 4444 3917 8131 5296 9870 2943 5054 3636 7417 1587 9804 4679 4374 4490
 3891 6919 7336 7207 6885 4991 5122 1421], shape=(50,), dtype=int32)

Positional maximum : 
 tf.Tensor(32, shape=(), dtype=int64)

Positional minimum : 
 tf.Tensor(49, shape=(), dtype=int64)


In [49]:
tf.random.set_seed(100)

B = tf.random.normal([2, 2])

print("Original Tensor : \n", B)

print("\nPositional maximum: \n", tf.argmax(B))

print("\nPositional minimum: \n", tf.argmin(B))

Original Tensor : 
 tf.Tensor(
[[ 0.16052227 -1.6597689 ]
 [-1.232133    0.5971658 ]], shape=(2, 2), dtype=float32)

Positional maximum: 
 tf.Tensor([0 1], shape=(2,), dtype=int64)

Positional minimum: 
 tf.Tensor([1 0], shape=(2,), dtype=int64)


## Squeezing a Tensor (Removing all single dimensions)

In [50]:
tf.random.set_seed(42)

C = tf.constant(tf.random.uniform(shape = [50]), shape = (1, 1, 1, 1, 50))

C, C.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [51]:
C_squeezed = tf.squeeze(C) # squeeze remove dimensions of size 1 from the shape of a Tensor

C_squeezed, C_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-Hot encoding Tensors

In [52]:
# Create a list of indices

list = [0, 1, 2, 3] # could be red, green, blue, purple

depth = list[tf.argmax(list)] + 1

one_hot = tf.one_hot(list, depth)

one_hot

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

Specify custom values for one-hot encoding

In [53]:
one_hot = tf.one_hot(list, depth, on_value = 'Yes', off_value = 'No') # Can also use numbers in the on and off values

one_hot

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

#### Math operations

* Squaring
* Log
* Square Root
* Power
* Negative
* Real

In [54]:
D = tf.range(0, 10)

D

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [55]:
# Square of the Tensor D

D_square = tf.square(D)

D_square

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [56]:
# Square root of the Tensor D

# D_square_root = tf.math.sqrt(D)  ERROR : Method requires non-int data type  

D_square_root = tf.math.sqrt(tf.cast(D, dtype = tf.float16))

D_square_root

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([0.   , 1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828,
       3.   ], dtype=float16)>

In [57]:
# Log of the Tensor D

# D_log = tf.math.log(D)  ERROR: Method requires non-int data type

D_log = tf.math.log(tf.cast(D, dtype = tf.float16))

D_log

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([  -inf, 0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 ,
       2.08  , 2.197 ], dtype=float16)>

In [58]:
# Negative

E = tf.range(-9, 0)

tf.math.negative(E)  # Compute numerical negative value element-wise.

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2, 1])>

In [59]:
# Power

X = tf.constant([1, 2, 3, 4])

Y = tf.constant([4, 3, 2, 1])

tf.math.pow(X, Y) # Computes the power of one value to another

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 8, 9, 4])>

In [60]:
# Real

F = tf.constant([3 + 8j, 4 + 2j])

tf.math.real(F) # Returns real part of the complex Tensor

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([3., 4.])>

### Tensors and NumPy

Tensors interacts beautifully with NumPy arrays.

In [61]:
# Create tensor directly from numpy arrays

G = tf.constant(np.arange(0, 9))

# Convert Tensor back to NumPy array

print("Tensor convert back to NumPy array: \n", np.array(G))

print("\nType: \n", type(np.array(G)))

print("\nType: \n", type(G))

Tensor convert back to NumPy array: 
 [0 1 2 3 4 5 6 7 8]

Type: 
 <class 'numpy.ndarray'>

Type: 
 <class 'tensorflow.python.framework.ops.EagerTensor'>


In [62]:
# Convert G tensor into NumPy arrays

G, type(G), G.numpy(), type(G.numpy())

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>,
 tensorflow.python.framework.ops.EagerTensor,
 array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 numpy.ndarray)

In [63]:
# The default types of each are slightly different

numpy_H = tf.constant(np.array([2, 2.]))

tensor_H = tf.constant([2, 2.])

# Check the data types of each

numpy_H.dtype, tensor_H.dtype

(tf.float64, tf.float32)

### Tensors Practice

In [64]:
# Numpy array created
arr = np.arange(1, 101)

# Convert NumPy array into Tensor
I = tf.constant(arr)

# Now reshape Tensor
I = tf.reshape(I, shape = (1, 10, 10, 1))

# Now remove all one dimensions from the tensor
I = tf.squeeze(I)

I

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])>

In [65]:
# First we make numpy array using random mehtod
arr = np.random.randint(0, 2, 30)

# Convert numpy array into tensor
J = tf.constant(arr)

# Now, we one-hot encode this Tensor

depth = arr[tf.argmax(arr)] + 1

J = tf.one_hot(J, depth)

J

<tf.Tensor: shape=(30, 2), dtype=float32, numpy=
array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]], dtype=float32)>

### 🛠 Exercises
1. Create a vector, scalar, matrix and tensor w. ith values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors.  you created in 1.
3. Create two tensors containing random values . between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 us. ing matrix multiplication.
5. Multiply the two tensors you created in 3 us. ing dot product.
6. Create a tensor with random values between 0.  and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor yo. u created in 6.
8. Created a tensor with random values of shape.  [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your o. wn choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 910

In [66]:
# 1. Create a vector, scalar, matrix and tensor w. ith values of your choosing using tf.constant().

scalar = tf.constant(2)

vector = tf.constant([5, 10])

matrix = tf.constant([
    [5, 10],
    [10, 5]
])

Tensor = tf.constant([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

In [67]:
# 2. Find the shape, rank and size of the tensors.  you created in 1.

# Scalar

print("SCALAR")

print("\nscalar shape: ", scalar.shape)

print("\nscalar rank: ", scalar.ndim)

print("\nscalar size: ", tf.size(scalar))

# Vector

print("\n\nVECTOR")

print("\nvector shape: ", vector.shape)

print("\nvector rank: ", vector.ndim)

print("\nvector size: ", tf.size(vector))

# Matrix

print("\n\nMATRIX")

print("\nmatrix shape: ", matrix.shape)

print("\nmatrix rank: ", matrix.ndim)

print("\nmatrix size: ", tf.size(matrix))

# Tensor

print("\n\nTENSOR")

print("\nTensor shape: ", Tensor.shape)

print("\nTensor rank: ", Tensor.ndim)

print("\nTensor size: ", tf.size(Tensor))

SCALAR

scalar shape:  ()

scalar rank:  0

scalar size:  tf.Tensor(1, shape=(), dtype=int32)


VECTOR

vector shape:  (2,)

vector rank:  1

vector size:  tf.Tensor(2, shape=(), dtype=int32)


MATRIX

matrix shape:  (2, 2)

matrix rank:  2

matrix size:  tf.Tensor(4, shape=(), dtype=int32)


TENSOR

Tensor shape:  (2, 2, 2)

Tensor rank:  3

Tensor size:  tf.Tensor(8, shape=(), dtype=int32)


In [68]:
# 3. Create two tensors containing random values . between 0 and 1 with shape [5, 300].

X = tf.constant(np.random.rand(5, 300))

Y = tf.constant(np.random.rand(5, 300))
X, Y

(<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
 array([[0.29298498, 0.3260656 , 0.24269316, ..., 0.18688763, 0.94121964,
         0.93631441],
        [0.52624151, 0.89508578, 0.7806746 , ..., 0.21445425, 0.41852687,
         0.52538583],
        [0.27811583, 0.62495325, 0.75899346, ..., 0.43375316, 0.4565087 ,
         0.72961724],
        [0.85420974, 0.67526664, 0.18703783, ..., 0.89531753, 0.97232674,
         0.90242706],
        [0.38383189, 0.56338666, 0.99655425, ..., 0.2365514 , 0.77318739,
         0.78350802]])>,
 <tf.Tensor: shape=(5, 300), dtype=float64, numpy=
 array([[0.01106011, 0.40803138, 0.21996749, ..., 0.99024771, 0.86721526,
         0.35816464],
        [0.99118348, 0.72627491, 0.00496583, ..., 0.56753955, 0.89884497,
         0.58088047],
        [0.83812812, 0.40898245, 0.95229057, ..., 0.93521469, 0.78266321,
         0.21252539],
        [0.09215378, 0.40766095, 0.1033542 , ..., 0.93123808, 0.59725685,
         0.4086864 ],
        [0.86500355, 0.59631599

In [69]:
# 4. Multiply the two tensors you created in 3 us. ing matrix multiplication.

# Both are incompatible. so, first we reshape one of the tensor to make compatible for matrix multiplication

Y = tf.reshape(Y, shape = (300, 5))

result = tf.matmul(X, Y)

result

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[67.47476675, 75.01338783, 74.47959945, 72.73301255, 72.69060614],
       [69.51556439, 74.33247585, 74.74047982, 72.82359975, 73.85145418],
       [66.12649171, 70.11072739, 72.31522807, 71.25736955, 70.38528813],
       [67.43656939, 74.13863297, 75.48903971, 76.09569471, 75.16639042],
       [73.05674976, 76.23361755, 79.3328778 , 73.96130312, 75.70766751]])>

In [70]:
# 5. Multiply the two tensors you created in 3 us. ing dot product.

tf.tensordot(X, Y, axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[67.47476675, 75.01338783, 74.47959945, 72.73301255, 72.69060614],
       [69.51556439, 74.33247585, 74.74047982, 72.82359975, 73.85145418],
       [66.12649171, 70.11072739, 72.31522807, 71.25736955, 70.38528813],
       [67.43656939, 74.13863297, 75.48903971, 76.09569471, 75.16639042],
       [73.05674976, 76.23361755, 79.3328778 , 73.96130312, 75.70766751]])>

In [71]:
# 6. Create a tensor with random values between 0.  and 1 with shape [224, 224, 3].

tf.random.set_seed(42)
X = tf.random.uniform(shape = [244, 244, 3])

X

<tf.Tensor: shape=(244, 244, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.14993274, 0.95743346, 0.0678556 ],
        [0.33755875, 0.2586832 , 0.31682265],
        [0.12932086, 0.6521549 , 0.6951654 ]],

       [[0.26241148, 0.36942792, 0.53326666],
        [0.2040397 , 0.21521878, 0.48851562],
        [0.5410471 , 0.55548096, 0.46440542],
        ...,
        [0.9536427 , 0.66850245, 0.50709856],
        [0.560426  , 0.6647233 , 0.1626333 ],
        [0.56197023, 0.4659928 , 0.8837141 ]],

       [[0.67773116, 0.88375974, 0.7615204 ],
        [0.53757155, 0.5554961 , 0.3356905 ],
        [0.7514802 , 0.10988402, 0.46292984],
        ...,
        [0.28655422, 0.00708723, 0.39797664],
        [0.32293415, 0.68600273, 0.2258904 ],
        [0.3624704 , 0.2741145 , 0.6718725 ]],

       ...,

       [[0.1581651 , 0.0120461 , 0.37919486],
        [0.50

In [72]:
#7. Find the min and max values of the tensor yo. u created in 6.

min = tf.math.reduce_min(X).numpy()

max = tf.math.reduce_max(X).numpy()

print("min: ", min, "\n\nmax: ", max)

min:  3.5762787e-07 

max:  0.999998


In [73]:
# 8. Created a tensor with random values of shape.  [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

Tensor = tf.random.uniform([1, 224, 224, 3])

print("Origianl Tensor: ", Tensor.shape)

# Now, we squeeze this Tensor

squeezed_Tensor = tf.squeeze(Tensor)

print("\nSqueezed Tensor: ", squeezed_Tensor.shape)

Origianl Tensor:  (1, 224, 224, 3)

Squeezed Tensor:  (224, 224, 3)


In [74]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

Tensor = tf.constant([10, 4, 5, 12, 56, 91, 75, 32, 43, 90])

max_index = tf.argmax(Tensor).numpy()

Tensor[max_index], max_index

(<tf.Tensor: shape=(), dtype=int32, numpy=91>, 5)

In [75]:
# 10. One-hot encode the tensor you created in 9

depth = Tensor[max_index] + 1

Tensor_one_hot = tf.one_hot(Tensor, depth)

Tensor_one_hot

<tf.Tensor: shape=(10, 92), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 